import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex shadow-xs shadow-black p-4 justify-end bg-slate-400">
          <Link href={"#"} className="p-4">Home</Link>
          <Link href={"#"} className="p-4">Home</Link>
          <Link href={"#"} className="p-4">Home</Link>

        </header>
        {children}
        <footer className="flex shadow-xs shadow-black p-4 bg-slate-400">
        <h6>Footer</h6>
        </footer>
      </body>
    </html>
  );
}
